//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mono.App.SelfPublishConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mono.App.SelfPublishConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;online.css&quot;&gt;
        ///	&lt;title&gt;{0}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///	&lt;article&gt;
        ///	{1}
        ///	&lt;/article&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string HtmlBook {
            get {
                return ResourceManager.GetString("HtmlBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;{0}&lt;/h1&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;
        ///{2}.
        /// </summary>
        internal static string HtmlChapter {
            get {
                return ResourceManager.GetString("HtmlChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;{0}&lt;/h2&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        internal static string HtmlSection {
            get {
                return ResourceManager.GetString("HtmlSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % {0}
        ///% {1}
        ///% {2}
        ///
        ///{3}
        ///.
        /// </summary>
        internal static string MarkdownBook {
            get {
                return ResourceManager.GetString("MarkdownBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # {0}
        ///
        ///{1}
        ///
        ///{2}
        ///.
        /// </summary>
        internal static string MarkdownChapter {
            get {
                return ResourceManager.GetString("MarkdownChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## {0}
        ///
        ///{1}
        ///.
        /// </summary>
        internal static string MarkdownSection {
            get {
                return ResourceManager.GetString("MarkdownSection", resourceCulture);
            }
        }
    }
}
